Repository moevm/nosql2h22-courier, pull requests merged in 2022-11, with the labels that each got.

#20 fix singup request
  back/utils/auth.py
Labels: Ready, Check

#21 Запросы для mongo shell для инициализации бд
  back/db/autopark.json
  back/db/load.sh
  back/db/orders.json
  back/db/save.sh
  back/db/users.json
  back/initial_db
Labels: Ready

#22 accountant requests
  back/app.py
  back/requests/__init__.py
  back/requests/orders.py
Labels: Ready

#47 Available pages after login
  front/src/Actions/login.js
  front/src/App.js
  front/src/Components/bd.js
  front/src/Pages/Allorders.jsx
  front/src/Pages/ClientPages/MyOrders.jsx
  front/src/Pages/InfoPage/Loading.jsx
  front/src/Pages/InfoPage/NoAccess.jsx
  front/src/Pages/LogIn.jsx
  front/src/Pages/Main.jsx
  front/src/Routes/Access.js
  front/src/Routes/Routes.js
  front/src/index.scss
  front/src/layouts/Header.jsx
  front/src/layouts/NavLinks.jsx
  front/src/scss/Error.scss
Labels: Check
